/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParadisoRouteImport } from './routes/paradiso'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AzureRouteImport } from './routes/azure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperiencesIndexRouteImport } from './routes/experiences.index'
import { Route as ExperiencesYogaRouteImport } from './routes/experiences.yoga'
import { Route as ExperiencesSpaRouteImport } from './routes/experiences.spa'
import { Route as ExperiencesMassageRouteImport } from './routes/experiences.massage'
import { Route as ExperiencesKiteSurfingRouteImport } from './routes/experiences.kite-surfing'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadisoRoute = ParadisoRouteImport.update({
  id: '/paradiso',
  path: '/paradiso',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AzureRoute = AzureRouteImport.update({
  id: '/azure',
  path: '/azure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesIndexRoute = ExperiencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperiencesRoute,
} as any)
const ExperiencesYogaRoute = ExperiencesYogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => ExperiencesRoute,
} as any)
const ExperiencesSpaRoute = ExperiencesSpaRouteImport.update({
  id: '/spa',
  path: '/spa',
  getParentRoute: () => ExperiencesRoute,
} as any)
const ExperiencesMassageRoute = ExperiencesMassageRouteImport.update({
  id: '/massage',
  path: '/massage',
  getParentRoute: () => ExperiencesRoute,
} as any)
const ExperiencesKiteSurfingRoute = ExperiencesKiteSurfingRouteImport.update({
  id: '/kite-surfing',
  path: '/kite-surfing',
  getParentRoute: () => ExperiencesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azure': typeof AzureRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/paradiso': typeof ParadisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/experiences/kite-surfing': typeof ExperiencesKiteSurfingRoute
  '/experiences/massage': typeof ExperiencesMassageRoute
  '/experiences/spa': typeof ExperiencesSpaRoute
  '/experiences/yoga': typeof ExperiencesYogaRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azure': typeof AzureRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/paradiso': typeof ParadisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/experiences/kite-surfing': typeof ExperiencesKiteSurfingRoute
  '/experiences/massage': typeof ExperiencesMassageRoute
  '/experiences/spa': typeof ExperiencesSpaRoute
  '/experiences/yoga': typeof ExperiencesYogaRoute
  '/experiences': typeof ExperiencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azure': typeof AzureRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/paradiso': typeof ParadisoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
  '/experiences/kite-surfing': typeof ExperiencesKiteSurfingRoute
  '/experiences/massage': typeof ExperiencesMassageRoute
  '/experiences/spa': typeof ExperiencesSpaRoute
  '/experiences/yoga': typeof ExperiencesYogaRoute
  '/experiences/': typeof ExperiencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azure'
    | '/contact'
    | '/corporate'
    | '/experiences'
    | '/paradiso'
    | '/sitemap.xml'
    | '/weddings'
    | '/experiences/kite-surfing'
    | '/experiences/massage'
    | '/experiences/spa'
    | '/experiences/yoga'
    | '/experiences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azure'
    | '/contact'
    | '/corporate'
    | '/paradiso'
    | '/sitemap.xml'
    | '/weddings'
    | '/experiences/kite-surfing'
    | '/experiences/massage'
    | '/experiences/spa'
    | '/experiences/yoga'
    | '/experiences'
  id:
    | '__root__'
    | '/'
    | '/azure'
    | '/contact'
    | '/corporate'
    | '/experiences'
    | '/paradiso'
    | '/sitemap.xml'
    | '/weddings'
    | '/experiences/kite-surfing'
    | '/experiences/massage'
    | '/experiences/spa'
    | '/experiences/yoga'
    | '/experiences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AzureRoute: typeof AzureRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  ParadisoRoute: typeof ParadisoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paradiso': {
      id: '/paradiso'
      path: '/paradiso'
      fullPath: '/paradiso'
      preLoaderRoute: typeof ParadisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azure': {
      id: '/azure'
      path: '/azure'
      fullPath: '/azure'
      preLoaderRoute: typeof AzureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/': {
      id: '/experiences/'
      path: '/'
      fullPath: '/experiences/'
      preLoaderRoute: typeof ExperiencesIndexRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/experiences/yoga': {
      id: '/experiences/yoga'
      path: '/yoga'
      fullPath: '/experiences/yoga'
      preLoaderRoute: typeof ExperiencesYogaRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/experiences/spa': {
      id: '/experiences/spa'
      path: '/spa'
      fullPath: '/experiences/spa'
      preLoaderRoute: typeof ExperiencesSpaRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/experiences/massage': {
      id: '/experiences/massage'
      path: '/massage'
      fullPath: '/experiences/massage'
      preLoaderRoute: typeof ExperiencesMassageRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/experiences/kite-surfing': {
      id: '/experiences/kite-surfing'
      path: '/kite-surfing'
      fullPath: '/experiences/kite-surfing'
      preLoaderRoute: typeof ExperiencesKiteSurfingRouteImport
      parentRoute: typeof ExperiencesRoute
    }
  }
}

interface ExperiencesRouteChildren {
  ExperiencesKiteSurfingRoute: typeof ExperiencesKiteSurfingRoute
  ExperiencesMassageRoute: typeof ExperiencesMassageRoute
  ExperiencesSpaRoute: typeof ExperiencesSpaRoute
  ExperiencesYogaRoute: typeof ExperiencesYogaRoute
  ExperiencesIndexRoute: typeof ExperiencesIndexRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesKiteSurfingRoute: ExperiencesKiteSurfingRoute,
  ExperiencesMassageRoute: ExperiencesMassageRoute,
  ExperiencesSpaRoute: ExperiencesSpaRoute,
  ExperiencesYogaRoute: ExperiencesYogaRoute,
  ExperiencesIndexRoute: ExperiencesIndexRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AzureRoute: AzureRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  ParadisoRoute: ParadisoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
